language: go

go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - 1.11.x

before_install:
  - go get -t -v ./...

script:
  - go build github.com/johnstcn/fakeadog/cmd/fakeadog
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic github.com/johnstcn/fakeadog/pkg/parser

after_success:
  - bash <(curl -s https://codecov.io/bash)
