language: go

go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - tip

before_install:
  - go get -t -v ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic github.com/johnstcn/fakeadog/pkg/parser
  - go build github.com/johnstcn/fakeadog/cmd/fakeadog

after_success:
  - bash <(curl -s https://codecov.io/bash)